### PR TITLE
Add speaker and sponsors

### PR DESCRIPTION
**Pull request by yaigrie**

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
For the presented by and sponsors, we should keep it similar to last year (https://deploy-preview-447--eurorust.netlify.app/2023/):

* presented by Mainmatter should be on top of the sponsors and we shouldn't be shy to make our logo really big
* the sponsors need to be sorted top to bottom with the top/most expensive plans at the top and the lowest plans at the bottom (see https://deploy-preview-447--eurorust.netlify.app/sponsorship-prospectus.pdf) – logos should ideally also be decreasing in size so that the logos of the higher plan sponsors appear larger than those of lower plan sponsors

**Comment by yaigrie** [comment]
I kept the sizing from last year, I think we'll be able to see it if we add more sponsors
I removed the flexwrap so they're going into different rows now

Also I doubled the Mainmatter logo size :) 

I added some to my local install:

Screenshot 2024-04-18 at 12 11 02

**Review by marcoow — APPROVED** [review]
approving already but let's make the Sentry logo a little bit bigger so it's visibly bigger than the Rust Foundation logo and not so much smaller than ours

**Comment by emmasofiah2o** [comment]
@oscard0m is this ready to merge now? :)

**Comment by oscard0m** [comment]
> @oscard0m is this ready to merge now? :)

Not yet. I did not pushed the fix Marco asked for.

**Comment by emmasofiah2o** [comment]
Oki, I'll move the post to tomorrow, please let me know when this can be merged so we can merge and post at the same time :)

**Comment by oscard0m** [comment]
> approving already but let's make the Sentry logo a little bit bigger so it's visibly bigger than the Rust Foundation logo and not so much smaller than ours

✅

**Comment by emmasofiah2o** [comment]
Merging so I can announce Charlie :)

**Pull request merged**
