### PR TITLE
feat(sponsors): add CodSpeed as Head Partner

### PR DESCRIPTION
**Pull request by oscard0m**

### CODE REVIEW

**Comment by SaeLLo** [comment]
Can we maybe put the logos in one line? Otherwise, the importance of sentry looks less.

**Comment by oscard0m** [comment]
> Can we maybe put the logos in one line? Otherwise, the importance of sentry looks less.

This is how it looks to me in Mobile and Desktop:

| mobile | Desktop |
|--------|--------|
| CleanShot 2024-08-06 at 15 28 55@2x | CleanShot 2024-08-06 at 15 29 43@2x | 

What device are you using to preview this so it is more than one line?

As a reference, this is how we were doing this in Eurorust 2023:

CleanShot 2024-08-06 at 15 31 54@2x

**Comment by SaeLLo** [comment]
> What device are you using to preview this so it is more than one line?

I used the computer - so I checked the desktop version. in your screenshots it looks good.

**Comment by oscard0m** [comment]
> image
> Codspeed looks pretty big.

Let me check. Thanks for sharing the screenshot.

**Comment by oscard0m** [comment]
How does it look now @SaeLLo ?

**Review by SaeLLo — APPROVED** [review]

**Comment by SaeLLo** [comment]
Thank you. Looks good now!

**Pull request merged**
