### PR TITLE
Add impl Rooms

### PR DESCRIPTION
**Pull request by LukeMathWalker**
I assume we'll need an og-image here @IdeliaRisella.

### CODE REVIEW

**Review by marcoow — APPROVED** [review]

**Comment by LukeMathWalker** [comment]
Can you either approve on Gravity or invite me there as a collaborator @marcoow?

**Comment by IdeliaRisella** [comment]
Here are the og-images. Please review and leave feedback if you need any changes.

og-image-impl room #2
og-image-impl room #1

**Comment by LukeMathWalker** [comment]
I think we can avoid `#1` and `#2` in the OG image. Other than that, they look good to me!

**Comment by IdeliaRisella** [comment]
No worries, here's the edited version of the visual. Looking at the general content, we can just use one for both days. Let me know if it works: @LukeMathWalker 

og-image-impl room #1

**Comment by LukeMathWalker** [comment]
@IdeliaRisella could you fix the image today so that we can publish and send out comms about the `impl Room`?

**Comment by IdeliaRisella** [comment]
og-image-impl room - final

Here's the edited image. I believe it should be alright now.

**Pull request merged**
