### PR TITLE
add arm as Partner

### PR DESCRIPTION
**Pull request by marcoow**
Bildschirmfoto 2023-07-12 um 08 27 52

### CODE REVIEW

**Comment by davidhajba** [comment]
@marcoow 
the 'arm' logo looks huge comparing the other 2 in the row 
- I guess they should look equal - could you pls make it 20% smaller ?

**Comment by marcoow** [comment]
sure, done

**Review by davidhajba — APPROVED** [review]

**Review by SaeLLo — APPROVED** [review]

**Comment by SaeLLo** [comment]
@marcoow Can we merge?

**Comment by marcoow** [comment]
@SaeLLo yes, once approved feel free to merge these whenever is good for you

**Pull request merged**
