### PR TITLE
add Huawei as live stream partner

### PR DESCRIPTION
**Pull request by marcoow**
Bildschirmfoto 2023-07-13 um 12 14 11

### CODE REVIEW

**Review by oscard0m — APPROVED** [review]

**Review by SaeLLo — APPROVED** [review]

**Comment by SaeLLo** [comment]
Thanks! I will merge when payment is received

**Comment by davidhajba** [comment]
Huawei looks slightly bigger then Hightec, 
if we want them to look equal size Huawei should be reduced by 5%

**Comment by marcoow** [comment]
@davidhajba done

**Review by davidhajba — APPROVED** [review]

**Comment by emmasofiah2o** [comment]
Can this be merged or are we still waiting on payment?

**Comment by SaeLLo** [comment]
> Can this be merged or are we still waiting on payment?

@emmasofiah2o Yes, this is ready to be merged.

**Pull request merged**
