### PR TITLE
feat(sponsors): add BMW as 'partner' sponsor

### LINKED ISSUE #478: Add BMW as partner Sponsor
More details in https://www.notion.so/mainmatter/BMW-Car-IT-5d1fc1eb2dc14fba89286b4e92521222?pvs=4

### PR DESCRIPTION
**Pull request by oscard0m**
# 📘 Description
Adds BMW Car IT as `partner` sponsor

| before | after |
|--------|--------|
| CleanShot 2024-05-28 at 13 23 15@2x | CleanShot 2024-05-28 at 13 23 26@2x | 

# 📖 Context
fixes #478

### CODE REVIEW

**Comment by emmasofiah2o** [comment]
@oscard0m thanks! I think we need to add all logos together tho (see picture below). Do you need me to merge them in Sketch?
Untitled (1)

**Comment by emmasofiah2o** [comment]
Yes, it is written in the Notion page so I am assuming it was the company's directions

**Comment by oscard0m** [comment]
> Yes, it is written in the Notion page so I am assuming it was the company's directions

I'm going to create a different PR with that approach. I want to see how it looks (specially in mobile it may look too small).

**Comment by SaeLLo** [comment]
> Hmmm... are we sure about that? To me, those are 3 logos and won't look very good with the rest. They need to be monochrome logos so we can make them white for the design.

Yes, it has to look like mentioned on Notion.

**Comment by oscard0m** [comment]
Closed by Closed by https://github.com/mainmatter/eurorust.eu/pull/481

**Pull request closed without merging**
