### PR TITLE
2023 Schedule

### PR DESCRIPTION
**Pull request by marcoow**

### CODE REVIEW

**Comment by marcoow** [comment]
@oscard0m @davidhajba some data still missing but let's review already so this is good to go once we have the missing info

**Comment by davidhajba** [comment]
sure, here is my review:

* these times should be 'body-small' which is size 18 
Screenshot 2023-07-10 at 13 48 18

* these names should be 'body-small' which is size 18 too
Screenshot 2023-07-10 at 13 54 27

* this width should be max 600 px
Screenshot 2023-07-10 at 13 53 16

* there's no arrow in the button here
Screenshot 2023-07-10 at 13 56 02

*  these times should be 'body-small' which is size 18  
Screenshot 2023-07-10 at 13 57 16

* these headers should not be caps lock
Screenshot 2023-07-10 at 13 58 17

* this structure is missing
Screenshot 2023-07-10 at 14 07 32

* these pictures are too big
Screenshot 2023-07-10 at 14 08 48
should be this size (as in sketch)
Screenshot 2023-07-10 at 14 09 36

**Comment by marcoow** [comment]
@davidhajba addressed everything except

> this structure is missing

that leaves very little space for the talk title on mobile so I made it 2 rows

**Comment by davidhajba** [comment]
@marcoow thank you for the updates, 

If you think it's important enough, here are some further things:

* the spacing between rows are very tight, not the same as in Sketch
Screenshot 2023-07-11 at 10 00 57

* these distances are bigger than in Sketch, reducing them can make the page shorter
Screenshot 2023-07-11 at 10 03 09

* I would not suggest using extra fonts in the headers, looks different in different browsers and from typography perspective it doesn't work 
Screenshot 2023-07-11 at 10 04 50
Screenshot 2023-07-11 at 10 05 01

* on mobile the background is missing in the second half of the page
Screenshot 2023-07-11 at 10 08 09

* the hyphen should belong to the smaller green text and not to the white body
Screenshot 2023-07-11 at 10 11 18

* would be good to not separate names like this, but keep them together in the next row if possible
Screenshot 2023-07-11 at 10 13 14

* on mobile the portrait with the containers should be 150 px 
Screenshot 2023-07-11 at 10 16 59

**Comment by marcoow** [comment]
addressed what I had time for – we can always improve things later

**Review by davidhajba — APPROVED** [review]

**Review by oscard0m — CHANGES_REQUESTED** [review]
Speaker pages are not looking good on mobile:
image
image

If we don't have time to fix them, I would disable the links to them at least.

---

I have more feedback but I assume those are not critical and we don't have time/resources to check them now.

**Comment by marcoow** [comment]
@oscard0m fixed

**Review by oscard0m — APPROVED** [review]

**Comment by SaeLLo** [comment]
eurorust1

@marcoow Can you please use this pic of Max Ammann

**Pull request merged**
