### PR TITLE
Initial 2024 schedule

### PR DESCRIPTION
**Pull request by nchan0154**
You will probably just want to preview this locally as the change list is quite noisy!
- Adds initial schedule content for 2024
- Creates talk pages for individual talks
- Minor tweaks to speaker pages
- Cleans up some low-hanging accessibility issues

### CODE REVIEW

**Comment by marcoow** [comment]
@nchan0154 is this ready for review already? Can you request reviews for PRs as a signal the braches are ready (nobody will even know the branches/PRs exist otherwise)?

**Comment by nchan0154** [comment]
Ready for review now @marcoow

**Comment by nchan0154** [comment]
@marcoow 
> Let's move the dedicated workshop section into the event schedule below where we currently list all activities on the day before the main event (including the workshop) again anyway
Sure. Do you prefer the layout of the current dedicated section, or the more condensed layout in the schedule section for these?

For the others, I've pushed a new commit, take a look. It's may be more trouble than it's worth to have shared entries in the middle of the schedule if we're making it dynamic/accessible/mobile friendly since it increases complexity dramatically and I'm not even sure if the templating engine can handle it (I'm also thinking that most viewers will be mobile users when the conference time comes?), but hopefully this should work.

**Comment by marcoow** [comment]
> Sure. Do you prefer the layout of the current dedicated section, or the more condensed layout in the schedule section for these?

I'd say we want the workshops to blend in with the rest of the schedule so let's use the more condensed layout of that (still keeping the workshop description but we can remove the extra boxes around the workshops etc.)

**Comment by marcoow** [comment]
I think this is a bit confusing now with the times not aligning…

Bildschirmfoto 2024-07-08 um 08 13 26

Would it not be easier (and semantically fine) to use a `table` here (which would also make it easier to do things like `rowspan` etc.)?

**Comment by nchan0154** [comment]
> Would it not be easier (and semantically fine) to use a table here (which would also make it easier to do things like rowspan etc.)?

Yes, if we wanted to line these up we'd best use a table, with a hidden column for the time and `aria-hidden="true"` on the times within the cells. I think this layout wouldn't work for mobile though, so it would just be desktop only? Let me know if that works for you.

**Comment by marcoow** [comment]
So we need to have sth. that works on desktop and mobile and the times need to be aligned so it's not confusing. I guess we could also use a table **and** a `div` based layout and show/hide on desktop/mobile as needed?

**Comment by marcoow** [comment]
💁 We have around 60% desktop users but during the event I'd agree it's likely more mobile

**Comment by nchan0154** [comment]
@marcoow Changed the layout completely on desktop, hopefully this layout is more readable and clean for the two tracks.

**Review by marcoow — COMMENTED** [review]
Looks great! Please don't merge yet though as we need to orchestrate with the social media announcements etc.

**Review by marcoow — APPROVED** [review]

**Pull request merged**
