### PR TITLE
content changes

### PR DESCRIPTION
**Pull request by yaigrie**
for when the conference is over

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
Let's make sure all the sponsor logos have the same size – they are quite unevenly sized currently:

Bildschirmfoto 2023-10-11 um 11 18 05


Also, can you remove "Accessibility", "Cancellation Policy", "Sponsorships", "Covid Policy" from the main landing page (`/`)?

Please also remove the "Book your Ticket" button from the 2023 page.

**Review by marcoow — COMMENTED** [review]
Looks good overall (I made some small changes – make sure to get the latest code from GitHub) except some small things:

* the logo in the header that links to the homepage should link to /2023 for all pages under /2023
* under /2023 the footer should remain unchanged – we want to keep all the links we have now (only on the root page we want to remove all links except code of conduct and imprint)
* on the workshop pages, we need to remote the ticket-booking button as well: https://deploy-preview-415--eurorust.netlify.app/schedule/day/1/

**Comment by yaigrie** [comment]
I forgot to adjust the template src on the individual speakers/moderators/workshops etc
Now header & footer should work as expected everywhere :)

**Review by marcoow — APPROVED** [review]
Perfect, thanks Nora! Can you merge this Friday 18:00?

**Pull request merged**
