### PR TITLE
Add workshops section

### PR DESCRIPTION
**Pull request by oscard0m**
# 📓 Description
- Added workshops section in [`/homepage`](https://deploy-preview-325--eurorust.netlify.app/)
- Added [`/workshops`](https://deploy-preview-325--eurorust.netlify.app//workshops/) page
- Added [`/workshops/workshops/introduction-to-rust-for-web-developers`](https://deploy-preview-325--eurorust.netlify.app//workshops/introduction-to-rust-for-web-developers)
- Added [`/workshops/you-cant-fix-what-you-cant-see-telemetry-for-rust-apis`](https://deploy-preview-325--eurorust.netlify.app//workshops/you-cant-fix-what-you-cant-see-telemetry-for-rust-apis)

## 🔬 Preview links
- [`/homepage`](https://deploy-preview-325--eurorust.netlify.app/)
- [`/workshops`](https://deploy-preview-325--eurorust.netlify.app//workshops/)
- [`/workshops/workshops/introduction-to-rust-for-web-developers`](https://deploy-preview-325--eurorust.netlify.app//workshops/introduction-to-rust-for-web-developers)
- [`/workshops/you-cant-fix-what-you-cant-see-telemetry-for-rust-apis`](https://deploy-preview-325--eurorust.netlify.app//workshops/you-cant-fix-what-you-cant-see-telemetry-for-rust-apis)

# 🗺️ Context
https://www.notion.so/mainmatter/Web-Workshops-page-924eb3e314674089bdcc779939a4f1b9?pvs=4

### CODE REVIEW

**Comment by SaeLLo** [comment]
Ticket names on Ti.to got changed to "conference ticket: ..."

**Review by davidhajba — APPROVED** [review]

**Comment by oscard0m** [comment]
@SaeLLo Do we wait for Workshop Tickets to appear in Ti.to or are we ready to go live with this?

**Comment by SaeLLo** [comment]
> @SaeLLo Do we wait for Workshop Tickets to appear in Ti.to or are we ready to go live with this?

Please wait. We are still discussing the ticket price.

**Review by SaeLLo — APPROVED** [review]

**Comment by SaeLLo** [comment]
Ticket sale is live

**Comment by oscard0m** [comment]
> Ticket sale is live

@SaeLLo Just to double-check, does this mean we are ready to land 🚀 ?

**Review by SaeLLo — APPROVED** [review]

**Review by SaeLLo — APPROVED** [review]

**Pull request merged**
