### PR TITLE
Add Hightec workshop

### PR DESCRIPTION
**Pull request by marcoow**
This adds the Hightec workshop:

Bildschirmfoto 2023-07-28 um 15 51 32

### CODE REVIEW

**Review by oscard0m — APPROVED** [review]

**Comment by SaeLLo** [comment]
@marcoow HighTec will run the workshop together with veecle. 

Can you change the organization description to: "run by HighTec in collaboration with Veecle"

The workshop hosts are: 
- HighTec: Mario Cupelli (https://www.linkedin.com/in/mario-cupelli/)
- Veecle: Daniel Frassinelli (https://www.linkedin.com/in/daniel-frassinelli-5686b9286/)

**Comment by marcoow** [comment]
@SaeLLo done

**Comment by SaeLLo** [comment]
image

Something is wrong with the logo.

**Comment by SaeLLo** [comment]
image

**Comment by marcoow** [comment]
fixed

**Review by oscard0m — APPROVED** [review]

**Comment by SaeLLo** [comment]
@marcoow Can you use this pic of Mario instead?
MarioCupelli_HighTec

**Comment by SaeLLo** [comment]
@marcoow Please add the speaker bios: 
Mario:
Mario Cupelli is the CTO of HighTec EDV-Systeme GmbH a world-leading provider of safety
qualified compilers based on LLVM technology, a modern embedded multicore real-time
operating system PXROS-HR and offers ISO 26262 ASIL D qualified tools for embedded
software development. As a CTO of HighTec, he continues to drive the company’s business
strategy and advocate for open-source tools in embedded development.

Daniel:
Daniel Frassinelli is a developer and co-founder of Veecle, based in Berlin. He comes with a
strong security background and is now leading the development of a Rust operating system
and middleware for automotive usage.

**Comment by marcoow** [comment]
@SaeLLo fixed

**Review by SaeLLo — APPROVED** [review]

**Pull request merged**
