### PR TITLE
Announce 2025 

### PR DESCRIPTION
**Pull request by umbrellarocket**
- This year's content all moved to /2024
- Landing page modified to provide 2025's dates and general info about Eurorust

### CODE REVIEW

**Comment by marcoow** [comment]
@umbrellarocket there seems to be a problem – can you check?

**Comment by umbrellarocket** [comment]
Reached out to @oscard0m for support on this one

**Comment by oscard0m** [comment]
> Reached out to @oscard0m for support on this one

@umbrellarocket I pushed a fix and preview is working now.

**Comment by oscard0m** [comment]
@umbrellarocket are you taking this? If not let me know and I can take it.

**Comment by umbrellarocket** [comment]
@oscard0m Pls could you take it? Thank you!

**Comment by oscard0m** [comment]
Applied fixes @umbrellarocket

**Review by marcoow — APPROVED** [review]

**Pull request merged**
