### PR TITLE
add-speaker-scott

### PR DESCRIPTION
**Pull request by yaigrie**

### CODE REVIEW

**Review by oscard0m — APPROVED** [review]

**Comment by oscard0m** [comment]
@emmasofiah2o I updated this branch with latest changes in `main` branch (and resolved conflicts) ✅

**Comment by oscard0m** [comment]
> @oscard0m I wanted to publish this today, but it looks like there are conflicts. Could you please help?

Conflicts solved

**Comment by emmasofiah2o** [comment]
@oscard0m thank you, but is it normal for all checks to be failing?

**Comment by oscard0m** [comment]
> @oscard0m thank you, but is it normal for all checks to be failing?

nope! Taking a look into it right now

**Comment by oscard0m** [comment]
@emmasofiah2o fixed. All ✅ ✅ ✅ ✅ ✅

**Pull request merged**
