### PR TITLE
Add Rust Vienna

### PR DESCRIPTION
**Pull request by umbrellarocket**
- Rust Vienna as media sponsors
- The Rust Vienna meetup on Oct. 09

### CODE REVIEW

**Comment by umbrellarocket** [comment]
@SaeLLo I added an end time to the meetup post (starting time:19:00; I added 22:00 as end time) LMK if it's an issue

**Comment by SaeLLo** [comment]
Can we structure this like the other side-activities?

"19:00: Rust Vienna Get-Together at Centimeter Rathaus!!" as the title

**Comment by marcoow** [comment]
Let's remove the image to make it fit in better

**Comment by marcoow** [comment]
I think it's fine but why are we selling tickets for that? Isn't it much easier for everyone if they handle that via their meetup.com page?

**Comment by umbrellarocket** [comment]
@SaeLLo Can you pls see Marco's last comment [here](https://github.com/mainmatter/eurorust.eu/pull/593#issuecomment-2388811674)?

**Comment by SaeLLo** [comment]
@marcoow They asked me to do it via ti.to so the registration is easier. I agreed with them then that it would be no problem.  At the meetup page people would need to register first.

**Comment by SaeLLo** [comment]
This can be merged, no?

**Pull request merged**
